apis/urls.py
# basic URL Configurations
from django.urls import include, path
# import routers
from rest_framework import routers

from . import views

router = routers.DefaultRouter()

router.register(r'employees', views.EmployeeViewSet)

app_name = 'apis'


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('attendance/<str:date>/', views.AttendanceByDateView.as_view(), name='get_attendance_by_date'),
    path('update-attendance/', views.UpdateAttendanceView.as_view(), name='update_attendance'),
]

employee_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("users.urls") ),
    path('admindashboard/', include("admin_dashboard.urls") ),
    path('employee/', include("employees.urls") ),
    path('leave/', include("leave.urls") ),
    path('attendance/', include("attendance.urls") ),
    path('api/', include("apis.urls") ),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
    path('', views.index, name='index'),
    path('change_password/', views.change_password, name='change_password'),
    path('my_account/', views.my_account_view, name='my_account'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('view_profile/', views.view_profile_view, name='view_profile'),
    path('update-personal-details/', views.update_personal_details, name='update_personal_details'),
    path('update-bank-details/', views.update_bank_details, name='update_bank_details'),
    path('upload-document/', views.upload_document, name='upload_document'),
    path('leave_application/', views.leave_application_view, name='leave_applications'),

    path('logout/', views.logout_view, name='logout'),
]

employees/forms.py
from django import forms
from .models import EmployeeUpdate, Document


class PersonalDetailsForm(forms.ModelForm):
    class Meta:
        model = EmployeeUpdate
        fields = [
            'profile_edit','employee_id', 
            'email', 'phone_number', 'address', 'emergency_contact_name',
            'emergency_contact_number', 'emergency_contact_relationship'
        ]
        labels = {
            'email': 'Email',
            'phone_number': 'Phone Number',
            'address': 'Address',
            'emergency_contact_name': 'Emergency Contact Name',
            'emergency_contact_number': 'Emergency Contact Number',
            'emergency_contact_relationship': 'Emergency Contact Relationship'
        }
        widgets = {
            'employee_id': forms.HiddenInput(),
            'profile_edit': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        employee_id = kwargs.pop('employee_id', None)
        profile_edit = kwargs.pop('profile_edit', False)
        super(PersonalDetailsForm, self).__init__(*args, **kwargs)
        
        if employee_id is not None:
            self.fields['employee_id'].initial = employee_id

        self.fields['profile_edit'].initial = False

    def save(self, commit=True):
        instance = super(PersonalDetailsForm, self).save(commit=False)
        instance.profile_edit = False
        if commit:
            instance.save()
        return instance
    
class BankDetailsForm(forms.ModelForm):
    class Meta:
        model = EmployeeUpdate
        fields = [
            'bank_name', 'bank_account_number', 'ifsc_code', 'bank_branch'
        ]

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = [
            'employee_id', 'document_type', 'document_description', 'document_path', 'validated'
        ]
        widgets = {
            'employee_id': forms.HiddenInput(),
            'validated': forms.HiddenInput(),
            'document_path': forms.FileInput(attrs={'accept': 'image/*,application/pdf'})
        }
        labels = {
            'document_path': 'Upload Document',
            'document_type': 'Document Type',
            'document_description': 'Document Description'
        }
    
    def __init__(self, *args, **kwargs):
        employee_id = kwargs.pop('employee_id', None)
        validated = kwargs.pop('validated', False)
        super(DocumentForm, self).__init__(*args, **kwargs)
        
        if employee_id is not None:
            self.fields['employee_id'].initial = employee_id

        self.fields['validated'].initial = False

    def save(self, commit=True):
        instance = super(DocumentForm, self).save(commit=False)
        # You can ensure validated is always set to False here
        instance.validated = False
        if commit:
            instance.save()
        return instance

employees/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.messages import get_messages
from leave.forms import LeaveRequestForm

from .forms import PersonalDetailsForm, BankDetailsForm, DocumentForm
from django.contrib.auth.models import User
from .models import Employee, Document, EmployeeUpdate
from leave.models import LeaveRequest, Leave

def clear_messages(request):
    storage = messages.get_messages(request)
    for message in storage:
        pass

def group_required(group_name):
    def in_group(user):
        return user.is_authenticated and user.groups.filter(name=group_name).exists()
    return user_passes_test(in_group)

def validate_password(password):
    if len(password) < 8:
        return False, 'Password must be at least 8 characters long.'
    if not any(char.isdigit() for char in password):
        return False, 'Password must contain at least one digit.'
    if not any(char.isupper() for char in password):
        return False, 'Password must contain at least one uppercase letter.'
    if not any(char.islower() for char in password):
        return False, 'Password must contain at least one lowercase letter.'
    return True, None

def get_employee_profile_context(user):
    employee = get_object_or_404(Employee, user_account=user)
    employee_docs = Document.objects.filter(employee_id=employee.employee_id)
    
    updated_employee_personal = EmployeeUpdate.objects.filter(employee_id=employee, profile_edit=True).last()
    updated_employee_bank = EmployeeUpdate.objects.filter(employee_id=employee, bank_edit=True).last()

    personal_form = PersonalDetailsForm(
        initial={
            'employee_id': employee.employee_id,
            'profile_edit': False,
            'email': employee.email,
            'phone_number': employee.phone_number,
            'address': employee.address,
            'emergency_contact_name': employee.emergency_contact_name,
            'emergency_contact_number': employee.emergency_contact_number,
            'emergency_contact_relationship': employee.emergency_contact_relationship
        }
    )
    
    bank_form = BankDetailsForm(initial={
        'bank_name': employee.bank_name,
        'bank_account_number': employee.bank_account_number,
        'ifsc_code': employee.ifsc_code,
        'bank_branch': employee.bank_branch
    })
    
    context = {
        'employee': employee,
        'documents': employee_docs,
        'updated_employee_personal': updated_employee_personal,
        'updated_employee_bank': updated_employee_bank,
        'personal_form': personal_form,
        'bank_form': bank_form,
        'document_form': DocumentForm(employee_id=employee.employee_id, validated=False),
    }
    
    return context

@group_required('employee')
def index(request):
    user = get_object_or_404(User, username=request.user.username)
    employee = get_object_or_404(Employee, user_account=user)
    context = {'employee': employee}
    if user.check_password(f'{employee.first_name.lower()}@123'):
        return redirect('employees:change_password')
    return render(request, 'employees/index.html', context)

@group_required('employee')
def change_password(request):
    user = get_object_or_404(User, username=request.user.username)
    employee = get_object_or_404(Employee, user_account=user)
    context = {'employee': employee}
    if request.method == 'POST':
        current_password = request.POST.get('current_password')
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')
        if not user.check_password(current_password):
            context['error'] = 'Incorrect current password.'
        elif user.check_password(new_password):
            context['error'] = 'New password cannot be the same as the current password.'
        elif new_password != confirm_password:
            context['error'] = 'Passwords do not match.'
        else:
            valid, error = validate_password(new_password)
            if valid:
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)
                return redirect('employees:index')
            context['error'] = error
    return render(request, 'employees/change_password.html', context)

@group_required('employee')
def my_account_view(request):
    user = get_object_or_404(User, id=request.user.id)
    employee = get_object_or_404(Employee, user_account=user)

    context = {
        'user': user,
        'employee': employee,
    }

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'change_username':
            new_username = request.POST.get('new_username')
            if User.objects.filter(username=new_username).exists():
                context['username_error'] = 'Username already exists.'
            else:
                user.username = new_username
                user.save()
                messages.success(request, 'Username changed successfully.')
                return redirect('employees:my_account')

        elif action == 'change_password':
            current_password = request.POST.get('current_password')
            new_password = request.POST.get('new_password')
            confirm_password = request.POST.get('confirm_password')
            is_valid, error = validate_password(new_password)

            if not user.check_password(current_password):
                context['password_error'] = 'Current password is incorrect.'
            elif new_password != confirm_password:
                context['password_mismatch'] = 'Passwords do not match.'
            elif not is_valid: 
                context['password_error'] = error
            else:
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Password changed successfully.')
                return redirect('employees:my_account')

    return render(request, 'employees/my_account.html', context)

@group_required('employee')
def notifications_view(request):
    return render(request, 'employees/notifications.html')

@group_required('employee')
def logout_view(request):
    logout(request)
    request.session.flush()
    return redirect('users:login')

@group_required('employee')
def view_profile_view(request):
    context = get_employee_profile_context(request.user)
    clear_messages(request)
    return render(request, 'employees/view_profile.html', context)

@group_required('employee')
def update_personal_details(request):
    # Fetch the employee associated with the current user
    employee = get_object_or_404(Employee, user_account=request.user)
    clear_messages(request)  # Clear any existing messages

    if request.method == 'POST':
        # Check if the employee already has a pending profile edit
        if employee.has_profile_edit:
            messages.error(request, 'You already have a pending request to update your personal details.')
            return redirect('employees:view_profile')
        
        # Bind the form to the POST data
        form = PersonalDetailsForm(request.POST)

        if form.is_valid():
            # Check for changes between the form data and the current employee data
            update_fields = {}
            for field in form.cleaned_data:
                new_value = form.cleaned_data[field]
                if hasattr(employee, field):
                    old_value = getattr(employee, field)
                    if new_value != old_value and new_value is not None:
                        update_fields[field] = new_value
                        
            print("Form is valid. Update fields:", update_fields)

            if update_fields:
                try:
                    # Create a new EmployeeUpdate object with the changed fields
                    employee_update = form.save(commit=False)
                    employee_update.employee_id = employee
                    employee_update.profile_edit = True
                    employee_update.save()

                    # Mark the employee as having a pending profile edit
                    employee.has_profile_edit = True
                    employee.save()
                    print("EmployeeUpdate created successfully.")
                    
                    messages.success(request, 'Your personal details update has been saved and will be reflected after validation.')
                except Exception as e:
                    print("Error creating EmployeeUpdate:", e)
                    messages.error(request, 'There was an error saving your details. Please try again.')

            else:
                messages.info(request, 'No changes detected in your personal details.')

            return redirect('employees:view_profile')
        else:
            # Handle form errors
            print("Form is invalid. Errors:", form.errors)
            messages.error(request, 'Please correct the errors below.')

    else:
        # If the request method is GET, create a form pre-filled with the employee's current details
        form = PersonalDetailsForm(instance=employee)

    # Prepare the context for rendering the profile view
    context = get_employee_profile_context(request.user)
    context['personal_form'] = form  # Pass the form to the context

    # Render the profile view with the provided context
    return render(request, 'employees/view_profile.html', context)




employees/templates/employees/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Employee Management System{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <style>
      :root {
        --primary-color: #0b3d72;
        --secondary-color: #003d7a;
        --tertiary-color: #f5f5f5;
        --nav-color: #003a77;
      }
      * {
        box-sizing: border-box;
      }
      .global-body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      .header {
        background-color: var(--nav-color);
        color: #fff;
        height: 8vh;
        width: 100%;
        padding: 10px 0;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 1000;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .header h2 {
        margin: 2px 10px;
        font-size: 1.5em;
      }
      .header a#home-a {
        color: white;
        text-decoration: none;
      }
      .nav-right {
        display: flex;
        align-items: center;
      }
      .nav-right a {
        color: white;
        text-decoration: none;
        padding: 0 15px;
        font-size: 16px;
      }
      .nav-right a:hover {
        transform: scale(1.05);
      }
      .notifications {
        position: relative;
      }
      .notifications .badge {
        position: absolute;
        top: -5px;
        right: -5px;
        background-color: red;
        color: white;
        border-radius: 50%;
        padding: 5px;
        font-size: 12px;
      }
      .main-container {
        display: flex;
        width: 100%;
        margin-top: 8vh;
      }
      .menu-container {
        width: 20%;
        background-color: #f5f5f5;
        padding: 20px;
        border-right: 1px solid #ccc;
        position: fixed;
        top: 8vh;
        bottom: 0;
        left: 0;
        overflow-y: auto;
      }
      .content-container {
        width: 80%;
        margin-left: 20%;
        padding: 0px 20px;
      }
      .dashboard-button {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
        padding: 8px;
        background-color: var(--secondary-color); /* Primary color */
        color: #fff; /* Text color */
        text-align: center;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s ease, transform 0.2s ease,
          box-shadow 0.3s ease;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Subtle shadow for depth */
      }

      .dashboard-button:hover {
        background-color: var(--primary-color);
        transform: scale(1.03);
        box-shadow: 0 6px 8px rgba(0, 0, 0, 0.2);
      }

      input[type="number"] {
        appearance: textfield;
      }

      input[type="number"]::-webkit-outer-spin-button,
      input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0; /* Chrome, Safari, Edge, Opera */
      }

      .dashboard-button span.material-symbols-outlined {
        font-size: 20px;
        margin-right: 8px;
        vertical-align: middle;
        color: #fff;
      }

      .dashboard-button:hover span.material-symbols-outlined {
        color: #f0f0f0;
      }
    </style>
    {% block styles %} {% endblock %}
  </head>
  <body class="global-body">
    <header class="header">
      <a href="{% url 'employees:index' %}" id="home-a">
        <h2>EMS</h2>
      </a>
      <div class="nav-right">
        <div class="notifications">
          <a href="{% url 'employees:my_account' %}">Account</a>
          <a href="{% url 'employees:notifications' %}" class="right-menu"
            >Notifications</a
          >
        </div>
        <a href="{% url 'employees:logout' %}" class="right-menu"
          >Logout</a
        >
      </div>
    </header>
    <div class="main-container">
      <div class="menu-container">
        <a
          href="{% url 'employees:view_profile' %}"
          class="dashboard-button"
        >
          <span class="material-symbols-outlined"> edit </span>
          Update Profile
        </a>
        <a
          href="{% url 'employees:leave_applications' %}"
          class="dashboard-button"
        >
          <span class="material-symbols-outlined"> article </span>
          Leave Applications
        </a>
        
      </div>
      <div class="content-container">{% block content %} {% endblock %}</div>
    </div>
  </body>
</html>

employees/templates/employees/notifications.html
{% extends "employees/base.html" %}

{% load static %}

{% block title %}Notifications{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/notifications.css' %}" />
{% endblock %}

{% block content %}
<div class="notifications-container">
    <h2>Notifications</h2>
    <h4>No Notifications</h4>
</div>
{% endblock %}

employees/templates/employees/view_profile.html
{% extends "employees/base.html" %}
{% load static %}
{% block title %}View Profile{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/view_profile.css' %}" />
<link rel="stylesheet" href="{% static 'css/_message_popup.css' %}">
{% endblock %}

{% block content %}
<div class="profile-container">
  {% include '_message_popup.html' %}

  <!-- Personal Details Section -->
  <div class="section personal-details">
    <h3>Personal Details</h3>
    {% if employee.has_profile_edit %}
      <p>Your personal details update is currently under review. Requested changes:</p>
      <ul>
        {% if updated_employee_personal.email != employee.email %}
        <li>Email: {{ updated_employee_personal.email }}</li>
        {% endif %}
        {% if updated_employee_personal.phone_number != employee.phone_number %}
        <li>Phone Number: {{ updated_employee_personal.phone_number }}</li>
        {% endif %}
        {% if updated_employee_personal.address != employee.address %}
        <li>Address: {{ updated_employee_personal.address }}</li>
        {% endif %}
        {% if updated_employee_personal.emergency_contact_name != employee.emergency_contact_name %}
        <li>Emergency Contact Name: {{ updated_employee_personal.emergency_contact_name }}</li>
        {% endif %}
        {% if updated_employee_personal.emergency_contact_number != employee.emergency_contact_number %}
        <li>Emergency Contact Number: {{ updated_employee_personal.emergency_contact_number }}</li>
        {% endif %}
        {% if updated_employee_personal.emergency_contact_relationship != employee.emergency_contact_relationship %}
        <li>Emergency Contact Relationship: {{ updated_employee_personal.emergency_contact_relationship }}</li>
        {% endif %}
      </ul>
    {% endif %}
    <form class="grid-container" method="POST" action="{% url 'employees:update_personal_details' %}">
      {% csrf_token %}
      {{ personal_form.as_p }}
      {% if personal_form.errors %}
      <div class="form-group error-messages">
        <ul>
          {% for field in personal_form %}
          {% for error in field.errors %}
          <li>{{ error }}</li>
          {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <div class="button-group" id="personal-submit-cancel-button-div">
        <button type="submit" class="edit-button" id="submit-personal">Submit</button>
        <button type="button" class="cancel-button" id="cancel-personal">Cancel</button>
      </div>
    </form>
    <button class="update-button" id="update-personal-details">Update Personal Details</button>
  </div>

  <!-- Bank Account Details Section -->
  <div class="section bank-details">
    <h3>Bank Account Details</h3>
    {% if employee.has_bank_account_edit %}
      <p>Your bank details update is currently under review. Requested changes:</p>
      <ul>
        {% if updated_employee_bank.bank_name != employee.bank_name %}
        <li>Bank Name: {{ updated_employee_bank.bank_name }}</li>
        {% endif %}
        {% if updated_employee_bank.bank_account_number != employee.bank_account_number %}
        <li>Account Number: {{ updated_employee_bank.bank_account_number }}</li>
        {% endif %}
        {% if updated_employee_bank.ifsc_code != employee.ifsc_code %}
        <li>IFSC Code: {{ updated_employee_bank.ifsc_code }}</li>
        {% endif %}
        {% if updated_employee_bank.bank_branch != employee.bank_branch %}
        <li>Bank Branch: {{ updated_employee_bank.bank_branch }}</li>
        {% endif %}
      </ul>
    {% endif %}
    <form class="grid-container" method="POST" action="{% url 'employees:update_bank_details' %}">
      {% csrf_token %}
      {{ bank_form.as_p }}
      {% if bank_form.errors %}
      <div class="form-group error-messages">
        <ul>
          {% for field in bank_form %}
          {% for error in field.errors %}
          <li>{{ error }}</li>
          {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <div class="button-group" id="bank-submit-cancel-button-div">
        <button type="submit" class="edit-button" id="submit-bank">Submit</button>
        <button type="button" class="cancel-button" id="cancel-bank">Cancel</button>
      </div>
    </form>
    <button class="update-button" id="update-bank-details">Update Bank Account Details</button>
  </div>

  <!-- Documents Section -->
  <div class="section documents">
    <h3>Uploaded Documents</h3>
    <div class="documents-list">
      {% if documents %}
        <table>
          <thead>
            <tr>
              <th>Document Type</th>
              <th>Document Description</th>
              <th>Uploaded On</th>
              <th>Verification Status</th>
            </tr>
          </thead>
          <tbody>
            {% for document in documents %}
            <tr>
              <td><a href="{{ document.document_path.url }}" target="_blank">{{ document.document_type }}</a></td>
              <td>{{ document.document_description }}</td>
              <td>{{ document.uploaded_at|date:"d-M-Y" }}</td>
              <td>
                {% if document.verified %}
                <span class="verified">Verified</span>
                {% else %}
                <span class="unverified">Unverified</span>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>No documents uploaded.</p>
      {% endif %}
    </div>
    
    <form class="upload-document-form grid-container" method="POST" action="{% url 'employees:upload_document' %}" enctype="multipart/form-data">
      <h4>Upload New Document</h4>
      {% csrf_token %}
      {{ document_form.as_p }}
      {% if document_form.errors %}
      <div class="form-group error-messages">
        <ul>
          {% for field in document_form %}
          {% for error in field.errors %}
          <li>{{ error }}</li>
          {% endfor %}
          {% endfor %}
        </ul>
      </div>
      {% endif %}
      <button type="submit" class="edit-button doc-submit">Submit</button>
    </form>
  </div>
</div>


<script>
  let personalFormInitialValues = {};
  let bankFormInitialValues = {};

  document.addEventListener('DOMContentLoaded', function() {
    // Set the initial state of the buttons and fields
    initializeFormStates();
  });

  function initializeFormStates() {
    var buttonGroupDiv = document.getElementById('personal-submit-cancel-button-div');
    var updateButton = document.getElementById('update-personal-details');

    buttonGroupDiv.style.display = 'none';
    updateButton.style.display = 'block';

    buttonGroupDiv = document.getElementById('bank-submit-cancel-button-div');
    updateButton = document.getElementById('update-bank-details');

    buttonGroupDiv.style.display = 'none';
    updateButton.style.display = 'block';

    var fields = document.querySelectorAll(`.personal-details input`);
    var textareas = document.querySelectorAll(`.personal-details textarea`);

    fields.forEach(field => {
      field.disabled = true;
    });
    textareas.forEach(field => {
      field.disabled = true;
    });

    fields = document.querySelectorAll(`.bank-details input`);
    textareas = document.querySelectorAll(`.bank-details textarea`);

    fields.forEach(field => {
      field.disabled = true;
    });
    textareas.forEach(field => {
      field.disabled = true;
    });
  }

  function toggleEditMode(section) {
    toggleButtonVisibility(section);
    toggleDisable(section);
  }

  function toggleButtonVisibility(section) {
    const buttonGroupDiv = document.getElementById(`${section}-submit-cancel-button-div`);
    const updateButton = document.getElementById(`update-${section}-details`);

    if (buttonGroupDiv.style.display === 'none') {
      buttonGroupDiv.style.display = 'block';
      updateButton.style.display = 'none';
    } else {
      buttonGroupDiv.style.display = 'none';
      updateButton.style.display = 'block';
    }
  }

  function toggleDisable(section) {
    const fields = document.querySelectorAll(`.${section}-details input`);
    const textareas = document.querySelectorAll(`.${section}-details textarea`);

    fields.forEach(field => {
      field.disabled = !field.disabled;
    });
    textareas.forEach(field => {
      field.disabled = !field.disabled;
    });
  }

  function saveInitialValues(section) {
    const form = document.querySelector(`.${section}-details`);
    const fields = form.querySelectorAll('input, textarea');

    if (section === 'personal') {
      personalFormInitialValues = {};
    } else if (section === 'bank') {
      bankFormInitialValues = {};
    }

    fields.forEach(field => {
      if (field.name) {
        if (section === 'personal') {
          personalFormInitialValues[field.name] = field.value;
        } else if (section === 'bank') {
          bankFormInitialValues[field.name] = field.value;
        }
      }
    });
  }

  function revertInitialValues(section) {
    const form = document.querySelector(`.${section}-details`);
    const fields = form.querySelectorAll('input, textarea');

    fields.forEach(field => {
      if (field.name) {
        if (section === 'personal') {
          field.value = personalFormInitialValues[field.name] || '';
        } else if (section === 'bank') {
          field.value = bankFormInitialValues[field.name] || '';
        }
      }
    });
  }

  document.getElementById('update-personal-details').addEventListener('click', function() {
    saveInitialValues('personal');
    toggleEditMode('personal');
  });

  document.getElementById('update-bank-details').addEventListener('click', function() {
    saveInitialValues('bank');
    toggleEditMode('bank');
  });

  document.getElementById('cancel-personal').addEventListener('click', function() {
    revertInitialValues('personal');
    toggleEditMode('personal');
  });

  document.getElementById('cancel-bank').addEventListener('click', function() {
    revertInitialValues('bank');
    toggleEditMode('bank');
  });
</script>

<script src="{% static 'scripts/_message_popup.js' %}"></script>

{% endblock %}